Load ISC meta data individually for each image
image-source-control/image-source-control pull request #158
Opened 2022-03-30 19:51 UTC by cnhk

fix #117

2022-03-30 22:36 UTC, cnhk commented
- One batch for all images at page load.
- Each inserted image use one extra ajax call.

2022-03-31 10:38 UTC, Galanos reviewed
Tested with 100 images in media library, looks good! Feels just as fast as before. Checked the following:
- [x] Media > Library overview
- [x] Media > Image Sources
- [x] Media > Library > (select random image) > (updated ISC fields)
- [x] Posts > All Posts > (edit existing post) > (insert image) > (select from Media Library) > (filled in ISC meta data)
- [x] Settings > Image Sources
- [x] Media > Image Sources > Debug > list post-image relations > (select random image) > Edit Media > (filled in ISC meta data)
- [x] (Global list on dedicated page in frontend)

2022-04-04 10:23 UTC, webzunft requested changes
Looks good. I just would like to get rid of that typo.

2022-04-04 10:23 UTC, webzunft commented on includes/gutenberg/isc-image-block.js
> +	var bacthLoad = function ( id, setAttributes ) {
typo in `bacthLoad`

2022-04-04 10:23 UTC, webzunft commented on includes/gutenberg/isc-image-block.js
> +			bacthLoad( id, setAttributes );
typo

2022-04-04 15:05 UTC, webzunft commented
If someone disables the REST API, wouldn’t they break the block editor completely? If they do, then the ISC block options don’t make sense for them, anyway. Or am I missing something?

2022-04-04 15:14 UTC, cnhk commented
That's right, Gutenberg can't work without the REST API.

2022-04-05 12:30 UTC, webzunft commented
@cnhk code looks good.
@Galanos would you mind testing the pull request on the test site, again?

2022-04-05 12:30 UTC, webzunft approved these changes

2022-04-05 13:40 UTC, Galanos reviewed
@webzunft Don’t mind at all! Again, tested with 100 images in media library. Checked the following again:
- [x] Media > Library overview
- [x] Media > Image Sources
- [x] Media > Library > (select random image) > (updated ISC fields)
- [x] Posts > All Posts > (edit existing post) > (insert image) > (select from Media Library) > (filled in ISC meta data)
- [x] Settings > Image Sources
- [x] Media > Image Sources > Debug > list post-image relations > (select random image) > Edit Media > (filled in ISC meta data)
- [x] (Global list on dedicated page in frontend)
Everything looking great. Didn’t notice any delays or other sluggish behavior.

2022-04-06 08:01 UTC, merged