Fix: prevents editing post without user input
image-source-control/image-source-control pull request #187
Opened 2022-05-22 16:24 UTC by cnhk

A page is considered to be edited because of modifying block attributes after loading ISC fields using custom REST API call.

ISC fields is now initialized using the Gutenberg data module (https://developer.wordpress.org/block-editor/reference-guides/data/), then saved using the `rest_after_insert_{$this->post_type}` hook.

fix #172

2022-05-22 16:30 UTC, cnhk commented
@Galanos I am not sure if that kind of stuff exists, but I will write it down here just in case.

Saving ISC fields on the widgets page might lead to "funny" behavior if there is a block that "has another block nested inside it" (I don't know if there is a plugin that do something like that - creates a block in which one can put another block and so on).

2022-05-23 15:48 UTC, Galanos requested changes
I ran the usual checks and noticed this halfway through:
- upon re-entering a previously edited post, all images lose their assigned license, and the field is empty
- at this time, the frontend still shows the licenses
- after editing and saving the post, the licenses disappear from the frontend

2022-05-23 16:25 UTC, cnhk commented
@Galanos 

> upon re-entering a previously edited post

What did you do exactly? Refreshing the page, or editing then not saving the changes then opening the page again? or something different?

2022-05-23 16:51 UTC, Galanos commented
@cnhk I did several tests to narrow down what exactly happens. Are you unable to reproduce it? The surefire way for me is:
- edit an existing post with two images
- set licenses
- save and leave post
- re-enter post
- look at license field of any of the two images

I can make a video if you’d like me to.

2022-05-23 17:16 UTC, cnhk commented
No need for a video. I think I have enough information.

2022-05-24 13:05 UTC, cnhk commented
@Galanos There was a typo in the code. Please re test it but don't use the "All Rights Reserved" license.

2022-05-25 06:55 UTC, Galanos approved these changes
Ran the following checks:
- [x] Media > Library overview
- [x] Media > Image Sources
- [x] Media > Library > (select random image) > (updated ISC fields)
- [x] Posts > All Posts > (edit existing post) > (insert image) > (select from Media Library) > (filled in ISC meta data)
- [x] Posts > All Posts > (re-enter previous post) > (check previous image for presence and correctness of ISC meta data)
- [x] Settings > Image Sources
- [x] Media > Image Sources > Debug > list post-image relations > (select random image) > Edit Media > (filled in ISC meta data)
- [x] (Global list on dedicated page in frontend)

Everything looking great; licenses are kept.

2022-05-25 09:33 UTC, webzunft commented
> Saving ISC fields on the widgets page might lead to "funny" behavior if there is a block that "has another block nested inside it" (I don't know if there is a plugin that do something like that - creates a block in which one can put another block and so on).

There are blocks that have other blocks in them, like "Group" or "Columns". @cnhk is that the kind of scenario that would be an issue here?

2022-05-27 13:58 UTC, cnhk commented
@Galanos @webzunft No problems with nested blocks.

2022-05-30 07:41 UTC, merged