Prevent losing focus when saving on media modal
image-source-control/image-source-control pull request #199
Opened 2022-06-25 06:21 UTC by cnhk

When editing attachment fields in the media modal, focus is lost after saving if the field is entered by tabbing or clicking on it when the previously edited field still has focus

fix #197

2022-06-25 09:39 UTC, webzunft commented
@cnhk thanks. I wasn’t aware that this also affected the block editor. @Galanos if you were then please also test it.

2022-06-25 09:40 UTC, cnhk commented
It's happening in every page that can possibly load the media library modal

2022-06-28 12:17 UTC, Galanos requested changes
I checked the two places that I know of:
- Media > Library > (select grid view) > (select image) > (sidebar in modal)
- Posts > All Posts > (create post) > (insert image) > (select button “Media Library” in empty image block) > (sidebar in modal)

Works like a charm—tabbing forwards, tabbing backwards, clicking into next field, clicking into license dropdown, … all is well.
The entered ISC metadata is saved to the attachment just as expected.

But the fix has spawned a new issue. It’s easiest to explain the replication steps:
1. Create a post, place an image, save the post, leave the post.
2. Re-enter the post.
3. Select the image, select “Replace” in the toolbar, select “Open Media Library”, Media Library modal pops up.
4. Without clicking anything, scroll down the sidebar of the preselected image.
5. Observe the ISC form fields missing.

The following applies:
- this does not happen with the current master branch
- selecting a different image, then reselecting the original image makes its ISC form fields appear
- _not_ selecting a different image, but leaving and re-entering the modal makes the original image’s ISC form fields appear, too
- to replicate once more, you need to leave and re-enter the post
- since in the “Media > Library” modal there’s no image preselected, it doesn’t apply there

2022-07-01 13:47 UTC, cnhk commented
I can't find an ideal (an not too complex) solution for this. First of all, I can't get the other solution in the core issue ticket to work, not enough info, so I dropped it.

So

1. We can tweak the current solution a bit, and apply it only on the `upload.php` page. When accessing the media modal frame from elsewhere (post page widgets etc.) the losing focus bug will be present.
2. Another approach is to return the focus manually to the input if it had it when WordPress re-render the attachment fields after a save event. But we do that only with ISC fields (no need to risk problems with others' attachment custom fields). Also if one is typing really fast in a textfield while the re-render process occurs, there might be a kind of stutter and one letter my be just swallowed. This is just in theory, I didn't start implementing yet.

2022-07-01 18:30 UTC, cnhk commented
@galanos I kind of created a mix of the two approaches from my previous comment. Please test the new fix. It prevents re-rendering custom attachment fields more than once. The potential side effect is that it can break the behavior of some custom fields, but only when it is really a very very complicated field (something coupled with a lot of complex custom JavaScript).

2022-07-07 08:21 UTC, Galanos commented
Note to self: Check freshly uploaded images for ISC form fields in the media library modal’s sidebar.

2022-07-07 11:07 UTC, Galanos commented
@cnhk I started testing and noticed … 
- when replacing an image with itself, changes made to its ISC fields in the Media Library modal within the block editor do reflect in the Media Library (opened in another tab), but **not** in the post’s block editor sidebar
- saving the post at this point replaces the ISC metadata with the unmodified, wrong sidebar values
- not saving the post and re-entering loads the modified, correct sidebar values for the image

I fear that this might be hard to read, so I’ll list the steps:
1. In a post, replace an image with ISC info through the toolbar’s “Replace” button.
2. In the modal, keep the preselected image selected, modify its ISC info.
3. Confirm the changes with the “Select” button, the modal closes, do not save post yet.
4. See unmodified ISC info in the sidebar, do not save post yet.
5. See modified ISC info in Media Library in second browser tab.
6. Save the post.
7. Refresh and see unmodified ISC info in Media Library.

But in the modal called from the block editor, the ISC fields appear for the preselected image and the focussing problem is still gone, though :)

2022-07-13 12:50 UTC, cnhk commented
@Galanos This is an unrelated issue. It is happening since we use WP's core functions to load/save ISC fields ([this](https://github.com/image-source-control/image-source-control/pull/187)) instead of custom AJAX calls.

Also, if we fix that bug (block sidebar on post/page after an edit in the modal), the user will be required to re-save the post/page since we did a modification on one or more attributes of a block on that page (not a big deal I think but worth mentioning).

2022-08-05 12:37 UTC, Galanos approved these changes
Given that the [last issue that I had raised](https://github.com/image-source-control/image-source-control/pull/199#issuecomment-1177423807) had no connection to the original focussing issue and that the latest commit was tested and found to solve the focussing _plus_ the missing sidebar ISC section, I have no objections to merging.

@cnhk Would you be so kind to please solve the remaining ReadMe conflict?

2022-08-06 12:57 UTC, cnhk commented
@Galanos Done

2022-08-08 13:03 UTC, webzunft requested changes

2022-08-08 13:03 UTC, webzunft commented on admin/admin.php
> +		if ( isset( $screen->id ) ) {
you could move the check to the top and return if it is false, so no brackets are needed.

2022-09-30 09:35 UTC, webzunft commented on admin/admin.php
> +		if ( isset( $screen->id ) ) {
@cnhk ping

2022-10-04 14:17 UTC, Galanos commented
@cnhk I’m a bit confused—I installed the current state of branch “i-197” on a staging site but the defocussing problem is back just as it was when we started. If I didn’t mix something up while downloading or installing (I did both twice to make sure), something must have gone wrong while committing between early July and now.
Could you please see for yourself? Thank you.

2022-10-06 12:30 UTC, cnhk commented
@Galanos My bad, I forgot one single `!` in https://github.com/image-source-control/image-source-control/pull/199/commits/234975d83c5b08640ea0b133dc88e2fa425569dc

Fixed now.

2022-10-24 12:41 UTC, merged